mysite/Doctor/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("doctorprofile/", views.profile, name="doctorprofile"),
    path('update_profile_image/', views.update_profile_image, name='update_profile_image'),
    path("showappointments/", views.appointment_list, name="showappointments"),
    path("appointment/<int:id>/", views.appointment, name="appointment"),
    path("prescription/<int:id>/", views.prescription, name="prescription"),
    path("CompleteAppointment/", views.complete_appointment, name="CompleteAppointment"),
]

mysite/guest/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.loginpage,name="login"),
    path("PatientRegistration/",views.patientregistration,name="Patientregistration"),
    path("WebadminHome/",views.webadmin,name='webadmin'),
    path("DoctorHome/",views.doctor,name='doctor'),
    path("PatientHome/",views.patient,name='patient'),
    path('logout/', views.logout_view, name='logout'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Webadmin.urls')),
    path('',include('Doctor.urls')),
    path('',include('Patient.urls')),
    path('',include('guest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/Doctor/models.py
from django.db import models
from django.utils import timezone
from Patient.models import AppoinmentTable

# Create your models here.
class Prescribition(models.Model):
    id = models.AutoField(primary_key=True)
    created_at = models.DateField(auto_now_add=True)
    time = models.TimeField(default=timezone.now().time())
    appoinmenet = models.ForeignKey(AppoinmentTable, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    prescription = models.TextField(max_length=500)

    def __str__(self):
        return self.title

mysite/Webadmin/models.py
from django.db import models

# Create your models here.
class DoctorTable(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    dob = models.DateField()
    image=models.ImageField(upload_to='profile',null=True,blank=True)
    specialized = models.TextField()
    email = models.EmailField(max_length=200)
    password = models.CharField(max_length=200)
    status = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class DepartmentTable(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"
    
class AssignDoctor(models.Model):
    id = models.AutoField(primary_key=True)
    doctor = models.ForeignKey(DoctorTable, on_delete=models.CASCADE)
    department = models.ForeignKey(DepartmentTable, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.doctor} {self.department}"

mysite/guest/models.py
from django.db import models

# Create your models here.
class PatientTable(models.Model):
    id = models.BigAutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='profile',null=True,blank=True)
    dob = models.DateField()
    email = models.EmailField(max_length=200)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class loginTable(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    password = models.CharField(max_length=100)
    type = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.email}"

mysite/Doctor/views.py
from datetime import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from . models import Prescribition
from guest.models import PatientTable
from Webadmin.models import DoctorTable
from Patient.models import AppoinmentTable, MedicalHistory
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

# Create your views here.
def doctor_required(view_func):
    def wrapper_func(request, *args, **kwargs):
        if request.session.get('type') != 'doctor':
            return redirect('login')
        return view_func(request, *args, **kwargs)
    return wrapper_func

@doctor_required
def profile(request):
    id = request.session.get('id')
    profile = DoctorTable.objects.get(id=id)
    return render(request, 'doctor/Home.html', {'profile': profile, 'id': id})

@doctor_required
def update_profile_image(request):
    id = request.session.get('id')
    profile = DoctorTable.objects.get(id=id)
    
    if request.method == 'POST':
        profile_image = request.FILES.get('profile_image')
        
        if profile_image:
            file_name = default_storage.save(profile_image.name, ContentFile(profile_image.read()))
            profile.image = file_name
            profile.save()
            
            messages.success(request, 'Profile image updated successfully.')
            return redirect('doctorprofile')
        else:
            messages.error(request, 'No image selected.')
    
    return render(request, 'doctor/profile.html', {'profile': profile})

def appointment_list(request):
    doctor_id = request.session.get('id')
    doctor = get_object_or_404(DoctorTable, id=doctor_id)
    appointments = AppoinmentTable.objects.filter(doctor_id=doctor_id)
    appointment_ids = appointments.values_list('id', flat=True)
    prescriptions = Prescribition.objects.filter(appoinmenet_id__in=appointment_ids).values_list('appoinmenet_id', flat=True)
    return render(request, 'doctor/appointment_list.html', {
        'appointments': appointments,
        'doctor': doctor,
        'prescriptions': prescriptions
    })


def complete_appointment(request):
    doctor_id = request.session.get('id')
    doctor = get_object_or_404(DoctorTable, id=doctor_id)
    # Get all completed prescriptions for the doctor
    completed_prescriptions = Prescribition.objects.filter(appoinmenet__doctor_id=doctor_id)
    # Extract the appointment IDs from the completed prescriptions
    appointment_ids = completed_prescriptions.values_list('appoinmenet_id', flat=True).distinct()
    # Get all the corresponding appointments
    appointments = AppoinmentTable.objects.filter(id__in=appointment_ids)
    return render(request, 'doctor/complete_appointment.html', {'appointments': appointments, 'doctor': doctor})


def appointment(request, id):
    data = AppoinmentTable.objects.get(id=id)
    pid = data.patient_id
    history = MedicalHistory.objects.get(patient_id=pid)
    current_prescriptions = Prescribition.objects.filter(appoinmenet_id=id)
    previous_prescriptions = Prescribition.objects.filter(appoinmenet__patient_id=pid)
    return render(request, 'doctor/appointment.html', {
        'data': data, 
        'history': history, 
        'current_prescriptions': current_prescriptions,
        'previous_prescriptions': previous_prescriptions
    })

def prescription(request, id):
    if request.method == 'POST':
        title = request.POST['title']
        prescription_text = request.POST['prescription']
        appointment = AppoinmentTable.objects.get(id=id)
        prescription = Prescribition(appoinmenet=appointment, title=title, prescription=prescription_text)
        prescription.save()
        return redirect('appointment', id=id)
    else:
        appointment = AppoinmentTable.objects.get(id=id)
        prescriptions = Prescribition.objects.filter(appoinmenet_id=id)
        return render(request, 'doctor/appointment.html', {'data': appointment, 'prescriptions': prescriptions})

mysite/templates/doctor/Home.html
{% extends "doctor/base.html" %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <h2 class="mb-4">Doctor Home Page</h2>
            <p>Welcome, Doctor</p>
            <p>This is your doctor home page content.</p>
            <div class="card mt-4">
                <div class="card-header">
                    <h4>Today's Appointments</h4>
                </div>
                <div class="card-body">
                    {% for appointment in appointments %}
                    <div class="card">
                        <div class="card-body">
                            <div class="appointment mb-3">
                                <h5>Patient: {{ appointment.patient.first_name }} {{ appointment.patient.last_name }}
                                </h5>
                                <p>Time: {{ appointment.time }}</p>
                            </div>
                            {% empty %}
                            <p>No appointments for today.</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-4">
        <div class="card-header">
            <h4>Pending Tasks</h4>
        </div>
        <div class="card-body">
            <!-- Replace with dynamic content -->
            {% for task in prescriptions %}
            <div class="card">
                <div class="card-body">
                    <div class="appointment mb-3">
                        <h5>Patient: {{ appointment.patient.first_name }} {{ appointment.patient.last_name }}
                        </h5>
                        <p>Time: {{ appointment.time }}</p>
                    </div>
                    {% empty %}
                    <p>No appointments for today.</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

mysite/templates/doctor/Index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>E-Hospital</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .navbar {
            background-color: #007bff !important;
        }
        .navbar-brand, .nav-link {
            color: #fff !important;
        }
        .signup-container {
            background: #fff;
            margin: 50px 0;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        .form-control {
            border-radius: 30px;
        }
        .form-floating label {
            color: #555;
        }
        .btn-primary {
            border-radius: 30px;
            background-color: #77aaff;
            border-color: #77aaff;
        }
        .btn-primary:hover {
            background-color: #559eea;
            border-color: #559eea;
        }
        footer {
            background-color: transparent;
            color: darkblue;
            padding: 10px 0;
            text-align: center;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <span class="navbar-brand">E-Hospital</span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>        
    </header>
    <main>
        {% block content %} {% endblock %}
    </main>
    <footer>
        <div class="container">
            <p>&copy; 2024 E-Hospital</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

mysite/templates/doctor/appointment.html
{% extends 'doctor/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <h2 class="mb-4">Appointment Details</h2>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th>Patient</th>
                            <td>{{ data.patient }}</td>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <td>{{ data.date }}</td>
                        </tr>
                        <tr>
                            <th>Time</th>
                            <td>{{ data.time }}</td>
                        </tr>
                        <tr>
                            <th>Message</th>
                            <td>{{ data.message }}</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <a href="#medicalHistoryModal" class="btn btn-success btn-sm" data-bs-toggle="modal">Medical History</a>
                                {% if not current_prescriptions %}
                                <a href="#prescriptionModal{{ data.id }}" class="btn btn-success btn-sm" data-bs-toggle="modal">Prescription</a>
                                {% endif %}
                                <a href="#previousPrescriptionsModal{{ data.patient.id }}" class="btn btn-success btn-sm" data-bs-toggle="modal">Previous Prescriptions</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Medical History -->
<div class="modal fade" id="medicalHistoryModal" tabindex="-1" aria-labelledby="medicalHistoryModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <h2 class="modal-title mb-2 text-center" id="medicalHistoryModalLabel"><b>Medical History</b></h2>
                <div class="mb-3">
                    <p><b>1)</b> Asthma, Diabetes, Epilepsy, etc. - conditions that you or any member of your family has</p>
                    <label for="FamilyTree" class="form-label">List these types of diseases:</label>
                    <div id="FamilyTree" style="color: rgb(38, 41, 222);">{{ history.FamilyTree|default_if_none:'' }}</div>
                </div>
                <div class="mb-3">
                    <p><b>2)</b> Any symptoms that you have like chest pain, shortness of breath, etc.</p>
                    <div id="symptoms" style="color: rgb(38, 41, 222);">{{ history.symptoms|default_if_none:'' }}</div>
                </div>
                <div class="mb-3">
                    <label class="form-label">3) Are you taking any medication?</label>
                    <div style="color: rgb(38, 41, 222);">
                        {% if history and history.takingMedication == 'Y' %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="listmedication" class="form-label">List Medication:</label>
                    <div id="listmedication" style="color: rgb(38, 41, 222);">{{ history.listmedication|default_if_none:'' }}</div>
                </div>
                <div class="mb-3">
                    <label class="form-label">4) Do you have any medication allergies?</label>
                    <div style="color: rgb(38, 41, 222);">
                        {% if history and history.medicationAllergies == 'Y' %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label">5) Do you use tobacco?</label>
                    <div style="color: rgb(38, 41, 222);">
                        {% if history and history.usetobacol == 'Y' %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </div>
                </div>
                <div class="mb-3">
                    <label for="alcohol" class="form-label">6) Alcohol Use:</label>
                    <div id="alcohol" style="color: rgb(38, 41, 222);">
                        {% if history and history.alcohol %}
                            {{ history.alcohol }}
                        {% else %}
                            Not specified
                        {% endif %}
                    </div>
                </div>
                <div class="modal-footer">
                    <label class="form-label">Last updated on: {{ history.date }}</label>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Prescription Modal -->
<div class="modal fade" id="prescriptionModal{{ data.id }}" tabindex="-1" aria-labelledby="prescriptionModalLabel{{ data.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <h2 class="modal-title mb-2 text-center" id="prescriptionModalLabel{{ data.id }}"><b>Prescription Details</b></h2>
                <form method="POST" action="{% url 'prescription' data.id %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="title" class="form-label">Title:</label>
                        <input type="text" id="title" name="title" class="form-control" value="{{ prescription.title|default_if_none:'' }}" required>
                    </div>
                    <div class="mb-3">
                        <label for="prescription" class="form-label">Prescription:</label>
                        <textarea id="prescription" name="prescription" class="form-control" rows="5" required>{{ prescription.prescription|default_if_none:'' }}</textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">Save</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Previous Prescriptions Modal -->
<div class="modal fade" id="previousPrescriptionsModal{{ data.patient.id }}" tabindex="-1" aria-labelledby="previousPrescriptionsModalLabel{{ data.patient.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <h2 class="modal-title mb-2 text-center" id="previousPrescriptionsModalLabel{{ data.patient.id }}"><b>Previous Prescriptions</b></h2>
                {% for prescription in previous_prescriptions %}
                    <div class="mb-3">
                        <h5><b>Doctor:</b> {{ prescription.appoinmenet.doctor.first_name }} {{ prescription.appoinmenet.doctor.last_name }}</h5>
                        <p><b>Title:</b> {{ prescription.title }}</p>
                        <p><b>Prescription:</b> {{ prescription.prescription }}</p>
                        <p><b>Date:</b> {{ prescription.created_at }}</p>
                        <hr>
                    </div>
                {% empty %}
                    <p>No previous prescriptions found.</p>
                {% endfor %}
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

mysite/templates/doctor/appointment_list.html
{% extends 'doctor/base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-4">
        <h1>Appointment List</h1>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Patient</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Message</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for appointment in appointments %}
                        {% if not appointment.id in prescriptions %}
                            <tr>
                                <td>{{ appointment.id }}</td>
                                <td>{{ appointment.patient }}</td>
                                <td>{{ appointment.date }}</td>
                                <td>{{ appointment.time }}</td>
                                <td>{{ appointment.message }}</td>
                                <td>
                                   <a href="{% url 'appointment' appointment.id %}" class="btn btn-success btn-sm">Attend</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% empty %}
                        <tr>
                            <td colspan="6" class="text-center">No appointments found</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

mysite/templates/doctor/complete_appointment.html
{% extends 'doctor/base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-4">
        <h1>Attended Appointment List</h1>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Patient</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Message</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for appointment in appointments %}
                    <tr>
                        <td>{{ appointment.id }}</td>
                        <td>{{ appointment.patient }}</td>
                        <td>{{ appointment.date }}</td>
                        <td>{{ appointment.time }}</td>
                        <td>{{ appointment.message }}</td>
                        <td>
                           <a href="{% url 'appointment' appointment.id %}" class="btn btn-info btn-sm">Detail</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">No appointments found</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

mysite/templates/doctor/profile.html
{% extends "doctor/base.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor Profile</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .photo-container {
            text-align: center;
            padding: 20px;
        }

        .photo-container img {
            width: 100px;
            height: 100px;
            border-radius: 50%;
        }

        .form-group {
            margin: 10px 0;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Doctor Profile</h2>
        <div class="photo-container">
            {% if profile.image %}
            <img src="{{ profile.image.url }}" alt="Profile Photo">
            {% else %}
            <img src="{% static 'default-profile.jpg' %}" alt="Profile Photo">
            {% endif %}
            <br><br>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#updateProfileImageModal">
                Edit Photo
            </button>
        </div>

       <!-- Modal HTML structure -->
       <div class="modal fade" id="updateProfileImageModal" tabindex="-1" role="dialog" aria-labelledby="updateProfileImageModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateProfileImageModalLabel">Update Profile Image</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" enctype="multipart/form-data" action="{% url 'update_profile_image' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="profile_image">Choose Image:</label>
                            <input type="file" class="form-control-file" id="profile_image" name="profile_image">
                        </div>
                        <button type="submit" class="btn btn-primary">Update Image</button>
                    </form>
                </div>
            </div>
        </div>
    </div> 

        <div class="modal-body">
            <div class="row">
                {% for msg in messages %}
                <div class="alert alert-info">{{ msg }}</div>
                {% endfor %}
                <div class="col-md-6 mb-3">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="id_first_name" name="first_name"
                            placeholder="First Name" value="{{ profile.first_name }}" disabled>
                        <label for="id_first_name">First Name</label>
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="id_last_name" name="last_name"
                            placeholder="Last Name" value="{{ profile.last_name }}" disabled>
                        <label for="id_last_name">Last Name</label>
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="id_dob" name="dob" placeholder="Date of Birth"
                            value="{{ profile.dob }}" disabled>
                        <label for="id_dob">Date of Birth</label>
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="form-floating">
                        <textarea class="form-control" id="id_specialized" name="specialized" placeholder="Specialized"
                            disabled>{{ profile.specialized }}</textarea>
                        <label for="id_specialized">Specialized</label>
                    </div>
                </div>
                <div class="col-md-12 mb-3">
                    <div class="form-floating">
                        <input type="email" class="form-control" id="id_email" name="email" placeholder="Email"
                            value="{{ profile.email }}" disabled>
                        <label for="id_email">Email</label>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>
{% endblock content %}